SELECT ai.NAME, ai.DATETIME
FROM ANIMAL_INS AS ai
LEFT JOIN ANIMAL_OUTS AS ao ON ao.ANIMAL_ID = ai.ANIMAL_ID
WHERE ai.ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_OUTS)
ORDER BY ai.DATETIME ASC
LIMIT 3
OFFSET 0;