-- 코드를 입력하세요
SELECT fo.PRODUCT_ID, fp.PRODUCT_NAME, SUM(fo.AMOUNT) * fp.PRICE AS TOTAL_SALES
FROM FOOD_ORDER AS fo 
JOIN FOOD_PRODUCT AS fp ON fo.PRODUCT_ID = fp.PRODUCT_ID
WHERE YEAR(fo.PRODUCE_DATE) = '2022'
    AND MONTH(fo.PRODUCE_DATE) = '5'
GROUP BY fo.PRODUCT_ID
ORDER BY TOTAL_SALES DESC,
        fo.PRODUCT_ID ASC