SELECT 
    HOUR(a.DATETIME) AS HOUR,
    COUNT(*) AS COUNT
FROM
    ANIMAL_OUTS AS a
WHERE 
    HOUR(a.DATETIME) >= 9 
    AND HOUR(a.DATETIME) <= 19
GROUP BY
    HOUR(a.DATETIME)
ORDER BY
    HOUR(a.DATETIME);