SELECT DISTINCT a.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS a
JOIN CAR_RENTAL_COMPANY_CAR AS b ON a.CAR_ID = b.CAR_ID
WHERE MONTH(a.START_DATE) >= 10
    AND b.CAR_TYPE = '세단'
ORDER BY a.CAR_ID DESC