SELECT fi.ID, fn.FISH_NAME, fi.LENGTH
FROM FISH_INFO AS fi
JOIN FISH_NAME_INFO AS fn ON fi.FISH_TYPE = fn.FISH_TYPE
JOIN (SELECT FISH_TYPE, MAX(LENGTH) as max_length
      FROM FISH_INFO
      GROUP BY FISH_TYPE) AS max ON fi.FISH_TYPE = max.FISH_TYPE and fi.LENGTH = max.max_length
