SELECT 
	ub.TITLE, 
	ub.BOARD_ID, 
	ur.REPLY_ID, 
	ur.WRITER_ID, 
	ur.CONTENTS, 
	DATE_FORMAT(ur.CREATED_DATE, "%Y-%m-%d") AS CREATED_DATE
FROM 
	USED_GOODS_BOARD AS ub
	JOIN USED_GOODS_REPLY AS ur ON ur.BOARD_ID = ub.BOARD_ID
WHERE
	ub.CREATED_DATE LIKE '2022-10%'
ORDER BY
	ur.CREATED_DATE ASC,
	ub.TITLE ASC;