SELECT b.CATEGORY, SUM(bs.SALES) AS TOTAL_SALES
FROM BOOK_SALES AS bs
JOIN BOOK AS b ON b.BOOK_ID = bs.BOOK_ID
WHERE DATE_FORMAT(bs.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY b.CATEGORY
ORDER BY b.CATEGORY;
